# fendoris-verify configuration

spectator-radius: 100

spectator-spawn:
  world: "world"
  x: 0.0
  y: 100.0
  z: 0.0
  yaw: 90.0
  pitch: 0.0

messages:
  unverified_join: "You are unverified and cannot play yet.\nUse /verify to see instructions."
  verify_already: "You are already verified."
  verify_info: "Server rules and verification steps:\n1) Read the rules.\n2) Run /verify me to confirm."
  verify_incorrect: "Incorrect verification. Use /verify me."
  verify_cannot_reverify: "You are already verified. No action needed."
  verify_success: "Verification complete. You may now play."
  spectate_blocked: "You cannot spectate or teleport to players until you verify."
  unverify_done_operator: "Set %target% unverified.\nLast location: %x% %y% %z% in %world%."
  unverify_notified_player: "You were set to unverified by an operator."
  unverify_not_found: "User %target% does not exist or has no verification record."
  unverify_usage: "Usage: /unverify <username>"
  spectator_boundary_hit: "You cannot leave this area until you verify."
  commands_blocked: "You cannot use that command until you verify."
  spawn_set: "Spectator spawn set at %x% %y% %z% in %world%."
  not_player: "Only players can use this."
  no_permission: "You do not have permission."
  reload_done: "fendoris-verify reloaded."
