name: fendoris-verify
version: '1.0-SNAPSHOT'
main: me.kc1508.fendorisVerify.FendorisVerify
api-version: '1.21'

commands:
  verify:
    description: View rules and proceed to application
    permission: fendoris.verify.use
  apply:
    description: Submit a verification application
    permission: fendoris.verify.use
  applyseeoffline:
    description: Review pending applications submitted while no operators were online
    permission: fendoris.verify.admin
  applyaccept:
    description: Accept a player's application
    usage: /applyaccept <player>
    permission: fendoris.verify.admin
  applydeny:
    description: Deny a player's application
    usage: /applydeny <player>
    permission: fendoris.verify.admin
  applyreset:
    description: Reset a player's denied status so they can reapply
    usage: /applyreset <player>
    permission: fendoris.verify.admin
  unverify:
    description: Set a player to unverified
    permission: fendoris.verify.admin
  setspectatorspawnpoint:
    description: Set spectator spawn point
    permission: fendoris.verify.admin
  fendorisverifyreload:
    description: Reload fendoris-verify config and storage
    permission: fendoris.verify.admin

permissions:
  fendoris.verify.use:
    default: true
  fendoris.verify.admin:
    default: op
